version: 2.1
executors:
  base:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          # Bundlerのパス設定が書き換えられ`vendor/bundle`ではなくて`/usr/local/bundle`を参照してしまい`bundle exec`でエラーになる
          # Bundlerのconfigファイル(pathの設定がされたもの)をworkspaceで永続化し`vendor/bundle`を参照するようにするための設定
          BUNDLE_APP_CONFIG: .bundle
    working_directory: ~/dodonki1223/docker_sample_rails_6

commands:
  # 依存関係のキャッシュを行うコマンド類
  # 詳しくは https://circleci.com/docs/ja/2.0/caching/
  # Bundlerのキャッシュ系コマンド
  # https://circleci.com/docs/ja/2.0/caching/#bundler-ruby
  restore-bundle-cache:
    steps:
      - restore_cache:
          keys:
            - v1-gem-cache-docker-sample-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-docker-sample-
  save-bundle-cache:
    steps:
      - save_cache:
          key: v1-gem-cache-docker-sample-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - ~/.bundle
  # Yarnのキャッシュ系コマンド
  # https://circleci.com/docs/ja/2.0/caching/#yarn-node
  restore-yarn-cache:
    steps:
      - restore_cache:
          keys:
            - yarn-packages-docker-sample-v1-{{ checksum "yarn.lock" }}
            - yarn-packages-docker-sample-v1-
  save-yarn-cache:
    steps:
      - save_cache:
          key: yarn-packages-docker-sample-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  # Bundlerのインストール系コマンド
  install-bundler:
    steps:
      - run:
          name: Install bundler(2.1.2)
          command: gem install bundler:2.1.2
  bundle-install:
    steps:
      - run:
          name: Bundle install
          command: bundle check --path=vendor/bundle || bundle install --jobs=4 --retry=3 --path vendor/bundle

  # ワークスペース関連のコマンド
  save-workspace:
    steps:
      - persist_to_workspace:
          # working_directory からの相対パスか絶対パスを指定します
          root: .
          paths: .
  using-workspace:
    steps:
      - attach_workspace:
          # working_directory からの相対パスか絶対パスを指定します
          at: .

jobs:
  setup:
    executor: base
    steps:
      - checkout
      - restore-bundle-cache
      - install-bundler
      - bundle-install
      - save-bundle-cache
      - restore-yarn-cache
      - save-yarn-cache
      - save-workspace

workflows:
  version: 2.1
  main:
    jobs:
      - setup
